### ISSUE TITLE
ボタンをクリックしてからいずれかのonKeyDownをすると直後に操作したボタンのボーダーが描画されてしまう。

### ISSUE THREAD

**Issue by takumimunemura** [ao-spirogyra/react-book-viewer#7]
[![Image from Gyazo](https://i.gyazo.com/dc8528b86752ae61c945f31d1f2365fc.png)](https://gyazo.com/dc8528b86752ae61c945f31d1f2365fc)
ボタンクリックでページ遷移後，キー入力でページ遷移するとボタン要素のボーダーが表示される。

この問題は方向キー実装以前には確認されていませんでした。
border:none またはtransparentでも解決しませんでした。

**Comment by ao-spirogyra** [comment]
https://github.com/ao-spirogyra/react-book-viewer/pull/9 で修正したのでcloseします
